### ISSUE TITLE
Joining issue in elongated forms of be and similar characters

### ISSUE THREAD

**Issue by saadatm** [googlefonts/Gulzar#61]
When using the `swsh` feature, elongated form of final _be_ (and other _be_-like characters) does not have a smooth join with its preceding character:

![swash-bay-join](https://user-images.githubusercontent.com/6615143/195403833-3c7fe5c7-9e3c-457b-814a-8737ef779b36.png)

(Please view the above image in its original size. Text strings in the image: `متعجب پنپ شکست سمٹ`)

**Comment by simoncozens** [comment]
Thanks for the bug report; what's happening is that the swash substitution is happening after the glyph selection, because swsh is a discretionary feature. We might need to find a way of running glyph selection again after swsh happens.

**Comment by simoncozens** [comment]
(We also have no connection rules for BEfs1 and friends.)

**Comment by saadatm** [comment]
Thanks for the explanation. I am curious, though: why do swash forms of final _fe_ and _kaf_ not have the same joining issue?

```
hb-view --features="swsh" -o swsh-be-fe-kaf.svg Gulzar-Regular.ttf "لب لف لک"
```

![swsh-be-fe-kaf](https://user-images.githubusercontent.com/6615143/195511794-668a1ef8-3119-40be-81b4-c6c1b8610ca8.png)

(Red circle showing the rough join of swash _be_; green circles showing the smooth joins of swash _fe_ and _kaf_.)

I tried looking in Crowbar, but `FEfs1` and `KAFfs1` don't seem to have any additional rules than `BEfs1`'s. What am I missing?

**Comment by simoncozens** [comment]
Well, it's because FEfs1 and KAFfs2 have the same connection as FEf1 and KAFf1, so no changes need to be made to the next letter:

<img width="567" alt="Screenshot 2022-10-13 at 07 39 15" src="https://user-images.githubusercontent.com/106728/195520722-c7d3002e-8052-4f2e-b980-1e282572c068.png">

but BEf1 and BEfs1 have different connections, so we need to change the form of the next glyph to match:
<img width="453" alt="Screenshot 2022-10-13 at 07 39 52" src="https://user-images.githubusercontent.com/106728/195520861-a6abdc73-0667-4450-81e5-5ac0ebeeb444.png">

**Comment by saadatm** [comment]
Ah, I see! So, we need to select the appropriate glyph (of the preceding letter) that will match the connection of `BEfs1`, which is why you mentioned that we need to find a way of running glyph selection again after `swsh` happens. Thanks! :)
